version: "3.7"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    environment:
      - API_PORT

  webapp:
    build: ./webapp
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./webapp:/webapp
    depends_on:
      - api
    environment:
      - REACT_APP_API_ADRS
      - REACT_APP_SOURCE
